#!/bin/bash
# install-watchdog.sh — install com.eventpulse.watchdog.plist into ~/Library/LaunchAgents.
#
# Idempotent: safe to run multiple times.
#
#   ./scripts/install-watchdog.sh           # install + load
#   ./scripts/install-watchdog.sh --uninstall
#
# After install:
#   launchctl list | grep eventpulse.watchdog
#   cat runtime/watchdog-launchd.out.log
#   tail -f runtime/autonomous-loop/watchdog.log

set -eu

PROJECT_ROOT="${PROJECT_ROOT:-/Volumes/2TB filer/NEWSTRUCTURE-COPY}"
PLIST_SRC="$PROJECT_ROOT/scripts/com.eventpulse.watchdog.plist"
PLIST_DEST="$HOME/Library/LaunchAgents/com.eventpulse.watchdog.plist"
WRAPPER_DEST="$HOME/bin/run-watchdog.sh"
LABEL="com.eventpulse.watchdog"

if [ ! -f "$PLIST_SRC" ]; then
  echo "ERROR: $PLIST_SRC not found" >&2
  exit 1
fi

if [ "${1:-}" = "--uninstall" ]; then
  echo "[install-watchdog] unloading $LABEL"
  launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
  launchctl unload "$PLIST_DEST" 2>/dev/null || true
  rm -f "$PLIST_DEST" "$WRAPPER_DEST"
  echo "[install-watchdog] removed $PLIST_DEST and $WRAPPER_DEST"
  exit 0
fi

# 1. Self-contained wrapper at ~/bin (launchd sandbox blocks exec of
#    scripts on /Volumes/2TB filer; reads/writes to /Volumes still work).
mkdir -p "$(dirname "$WRAPPER_DEST")"
cat > "$WRAPPER_DEST" <<WRAPPER
#!/bin/bash
# Auto-generated by scripts/install-watchdog.sh — DO NOT EDIT BY HAND.
# Edit scripts/install-watchdog.sh instead and re-run it to regenerate.
set -eu
PROJECT_ROOT="$PROJECT_ROOT"
LOG_DIR="\$PROJECT_ROOT/runtime/autonomous-loop"
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:\$HOME/.local/bin:\$PATH"
cd "\$PROJECT_ROOT"
mkdir -p "\$LOG_DIR"
echo "[run-watchdog] PID=\$\$ \$(date -u +%Y-%m-%dT%H:%M:%SZ) starting argv=\$*"
exec npx tsx 09-MobileControl/watchdog/watchdog.ts "\$@"
WRAPPER
chmod +x "$WRAPPER_DEST"
echo "[install-watchdog] wrote $WRAPPER_DEST"

# 2. Plist into ~/Library/LaunchAgents (idempotent — unload first).
mkdir -p "$(dirname "$PLIST_DEST")"
cp "$PLIST_SRC" "$PLIST_DEST"

launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
launchctl unload "$PLIST_DEST" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST_DEST" 2>&1 || \
  launchctl load -w "$PLIST_DEST"

echo "[install-watchdog] installed $PLIST_DEST"
echo "[install-watchdog] loaded $LABEL"
echo
echo "Verify with:"
echo "  launchctl list | grep $LABEL"
echo "  cat /tmp/com.eventpulse.watchdog.out.log"
echo "  tail -n 50 $PROJECT_ROOT/runtime/autonomous-loop/watchdog.log"
