#!/bin/bash
# start-mobile-control.sh — start tmux session + mobile control server.
#
# Runs autonomous-loop.sh inside a tmux session named `eventpulse`, then
# starts the mobile control server. Disconnect from terminal → autonomous
# work continues. Reconnect via `tmux attach -t eventpulse`.

set -eu

PROJECT_ROOT="${PROJECT_ROOT:-/Volumes/2TB filer/NEWSTRUCTURE-COPY}"
PORT="${MOBILE_CONTROL_PORT:-8788}"
BIND="${MOBILE_CONTROL_BIND:-127.0.0.1}"

# Generate or read token. If MOBILE_CONTROL_TOKEN not set, generate and persist.
if [ -z "${MOBILE_CONTROL_TOKEN:-}" ]; then
  if [ -f "$PROJECT_ROOT/.env.mobile" ]; then
    set -a
    # shellcheck disable=SC1091
    . "$PROJECT_ROOT/.env.mobile"
    set +a
  fi
fi

if [ -z "${MOBILE_CONTROL_TOKEN:-}" ] || [ "${#MOBILE_CONTROL_TOKEN}" -lt 16 ]; then
  echo "Generating new MOBILE_CONTROL_TOKEN (32 hex) and persisting to .env.mobile"
  TOKEN=$(openssl rand -hex 32)
  cat > "$PROJECT_ROOT/.env.mobile" <<EOF
# Auto-generated by start-mobile-control.sh. Used by 09-MobileControl/server.ts.
MOBILE_CONTROL_TOKEN=$TOKEN
MOBILE_CONTROL_PORT=$PORT
MOBILE_CONTROL_BIND=$BIND
EOF
  chmod 600 "$PROJECT_ROOT/.env.mobile"
  echo "Token written to $PROJECT_ROOT/.env.mobile (mode 600)"
  echo
  echo "After installing Tailscale, open this URL on your phone:"
  echo "  http://<tailscale-ip>:$PORT/?token=$TOKEN"
  echo
  echo "Find your Tailscale IP with:  tailscale ip -4"
  echo
  export MOBILE_CONTROL_TOKEN="$TOKEN"
fi

# 1. tmux session (if not running).
if ! command -v tmux >/dev/null 2>&1; then
  echo "ERROR: tmux not installed. Install with: brew install tmux" >&2
  exit 1
fi

if tmux has-session -t eventpulse 2>/dev/null; then
  echo "tmux session 'eventpulse' already running"
else
  echo "Starting tmux session 'eventpulse' running autonomous-loop.sh…"
  tmux new-session -d -s eventpulse -n autonomous \
    -c "$PROJECT_ROOT" \
    "$PROJECT_ROOT/scripts/autonomous-loop.sh"
  sleep 1
fi

# 2. Start mobile control server.
echo "Starting mobile control server on http://$BIND:$PORT…"
cd "$PROJECT_ROOT"
exec npx tsx 09-MobileControl/server.ts