/**
 * 08-Agent/types/ai_image — Step A smoketest only.
 *
 * Step A is a tightly-scoped copyright-safe image pipeline that
 * (a) replaces 10 upstream event images with AI-generated ones,
 * (b) does NOT mutate any Supabase row, and (c) is feature-flagged.
 *
 * These types are deliberately scoped narrow — Step B will widen them.
 */

// ─── Safe prompt builder ──────────────────────────────────────────────────

/**
 * Input row for `buildSafePrompt()`. Mirrors the slice of events_public
 * the smoketest cares about; the script pulls only these columns from
 * Supabase and discards the rest before constructing the prompt.
 */
export interface SafePromptInput {
  /** Canonical events_public.id (uuid). Used in the watermark. */
  id: string;
  /** Title in Swedish (preferred) or English. */
  title: string;
  /** Category slug (music, theater, film, etc.). */
  category_slug: string;
  /** Venue display name — will be replaced by a generic hint. */
  venue_name: string;
  /** City. Stockholm is the default; the script overrides empty. */
  city: string;
  /** Free vs paid — affects venue hint + light quality. */
  is_free: boolean;
  /** ISO 8601 start time — used to derive time-of-day hint. */
  start_time: string;
}

/**
 * Output of `buildSafePrompt()`. The script and tests work with this
 * object; only `prompt` + `negative_prompt` are sent to the model.
 */
export interface SafePromptResult {
  /** Final sanitized prompt, ≤ 900 chars, never empty. */
  prompt: string;
  /** Explicit "do not render" hint passed alongside the prompt. */
  negative_prompt: string;
  /** Style tags surfaced for the audit log (also embedded in prompt). */
  style_tags: string[];
  /**
   * sha256(canonical_prompt)[:16]. Stable for the same input set so
   * re-generation is idempotent and the audit log can spot drift.
   */
  prompt_hash: string;
  /** Which input fields actually shaped the prompt (used by tests). */
  sources_used: ReadonlyArray<keyof SafePromptInput>;
  /** True when a category-only fallback was used (short title, blocked). */
  fallback_used: boolean;
}

// ─── Image manifest ──────────────────────────────────────────────────────

/**
 * One entry in `runtime/ai-image-smoketest/index.json`. Generated by
 * `generate_ai_image_smoketest.ts`, read by the static middleware and
 * the `/agent/feed-ai-images` endpoint.
 */
export interface AiImageManifestEntry {
  /** Canonical events_public.id (uuid). */
  event_id: string;
  /** Title at the time of generation (denormalised so the endpoint
   *  doesn't need to re-query Supabase). */
  title: string;
  /** start_time at the time of generation. */
  start_time: string;
  /** Venue display name at the time of generation. */
  venue_name: string;
  /** Relative path inside the runtime dir, e.g. "images/<uuid>.png". */
  path: string;
  /** Sha256[:16] of the safe prompt — ties the file to its audit hash. */
  prompt_hash: string;
  /** ISO 8601 timestamp of when the image was generated. */
  generated_at: string;
  /** Model name (always "gpt-image-1" for Step A). */
  model: string;
  /** Optional cost estimate from the OpenAI response (USD). */
  cost_usd: number | null;
}

export interface AiImageManifest {
  /** Schema version so the index can evolve. */
  version: 1;
  /** Ordered list of generated entries. */
  entries: AiImageManifestEntry[];
}

// ─── Wire types for the agent API ────────────────────────────────────────

/**
 * Returned by `GET /agent/feed-ai-images`. The UI binds this shape
 * verbatim — no transformation needed in HomeScreen.
 *
 * `model` is the manifest's provider tag (e.g. `gpt-image-1`,
 * `flux-2-klein-4b`). Added 2026-08-23 so the UI can filter by
 * provider or show a per-card model chip (e.g. on the dedicated
 * `*`-tab smoketest screen).
 */
export interface FeedAiImagesResponse {
  events: Array<{
    id: string;
    title: string;
    start_time: string;
    venue_name: string;
    image_url: string;
    prompt_hash: string;
    generated_at: string;
    model: string;
    watermark: 'AI-genererad';
  }>;
  warnings: string[];
}

// ─── Brand / trademark list (Step A) ────────────────────────────────────

/**
 * Concrete venue + brand names that must never leak into the prompt.
 *
 * Step A starts with a small, Stockholm-relevant set. Step B widens
 * this list. Adding to it is a decision point — see CLAUDE.md
 * "Generalization Protection Rule" for the cross-site verification
 * requirement.
 */
export const TRADEMARK_BLOCKLIST: ReadonlyArray<string> = [
  // Ticket platforms — never named in prompts.
  'ticketmaster',
  'eventbrite',
  'billetto',
  'kulturbiljetter',
  'ticnet',
  // Stockholm venues with strong visual identities.
  'konserthuset',
  'berwaldhallen',
  'kulturhuset',
  'cirkus',
  'mosebacke',
  'fotografiska',
  'moderna museet',
  // Branded Swedish acts — likeness risk.
  'abba',
  'kent',
  'the cardigans',
  'robyn',
  'avicii',
  'swedish house mafia',
  'tove lo',
  'eurovision',
  // Anti-overfit categories that frequently embed logos / photos.
  'venue logos',
  'brand name',
  'product placement',
];

/**
 * Generic venue hints returned by `venueTypeHint()`. Each is a
 * deliberately anonymous architectural description — no venue names,
 * no brand cues.
 */
export const VENUE_HINT_BUCKETS: ReadonlyArray<{
  hint: string;
  /** Match if any keyword appears in `category_slug` or `title`. */
  match: ReadonlyArray<string>;
}> = [
  { hint: '[small concert hall with warm stage lighting]', match: ['music', 'concert', 'band', 'dj', 'jazz', 'rock', 'punk', 'metal', 'orchestra'] },
  { hint: '[historic theater interior with red velvet seats]', match: ['theater', 'theatre', 'play', 'opera', 'musical', 'drama'] },
  { hint: '[gallery space with white walls and soft daylight]', match: ['exhibition', 'gallery', 'art', 'photo', 'photography', 'museum'] },
  { hint: '[bookshop reading corner with wooden shelves]', match: ['book', 'reading', 'author', 'lecture', 'talk', 'spoken', 'literature', 'poetry'] },
  { hint: '[outdoor park stage surrounded by autumn trees]', match: ['festival', 'outdoor', 'park', 'open-air'] },
  { hint: '[industrial club basement with low ceiling]', match: ['club', 'techno', 'electronic', 'rave', 'late night', 'dj-set'] },
  { hint: '[cinema hall with deep blue ambient light]', match: ['film', 'movie', 'cinema', 'screening', 'documentary'] },
  { hint: '[workshop room with tables and craft supplies]', match: ['workshop', 'craft', 'kids', 'family', 'class'] },
  { hint: '[community center hall with string lights]', match: ['community', 'meetup', 'social', 'family'] },
  // Catch-all.
  { hint: '[small urban event room with neutral decor]', match: [] },
];

// ─── Visual variation axes (Step A refinement, 2026-08-23) ────────────────

/**
 * Color palettes for the per-event seeded variation. Each entry is a
 * comma-separated color instruction injected into the final prompt.
 *
 * All terms are abstract color descriptors — no brand names, no
 * photographic terms (those are explicitly forbidden by the negative
 * prompt anyway). The audit grader in `tests/build_safe_prompt.test.ts`
 * verifies no term leaks a TRADEMARK_BLOCKLIST entry.
 */
export const PALETTES: ReadonlyArray<{ name: string; prompt: string }> = [
  { name: 'autumn-gold',       prompt: 'autumn gold, mustard yellow, burnt sienna, soft beige' },
  { name: 'winter-cool',       prompt: 'pale slate, ice blue, muted teal, soft white highlights' },
  { name: 'summer-soft',       prompt: 'sun-faded terracotta, sage green, dusty rose, cream' },
  { name: 'theatrical-drama',  prompt: 'deep burgundy, brass gold, charcoal black, candlelit amber' },
  { name: 'minimal-mono',      prompt: 'soft greys, bone white, charcoal accent, subtle warm undertones' },
  { name: 'risograph-pop',     prompt: 'flat dusty pink, electric teal, mustard yellow, off-white negative space' },
  { name: 'mossy-nordic',      prompt: 'forest green, lichen grey, ochre, fog blue' },
  { name: 'lavender-twilight', prompt: 'dusty purple, indigo, soft pink horizon, gunmetal blue' },
];

/**
 * Art mediums — vary the *how* of rendering so two events at the same
 * venue end up with visibly different surface texture.
 *
 * Same constraint as PALETTES: no trademarks, no photographic/realistic
 * terms.
 */
export const MEDIUMS: ReadonlyArray<string> = [
  'watercolor with visible brushstrokes',
  'oil paint with impasto texture',
  'gouache with flat color fields',
  'linocut print with bold contrasts',
  'risograph with offset misregistration',
  'pastel on grainy paper',
  'pencil and watercolor sketch',
  'digital matte painting',
];

/**
 * Compositions — vary the *where the camera is* (metaphorically) so two
 * events at the same venue produce different framing.
 */
export const COMPOSITIONS: ReadonlyArray<string> = [
  'wide cinematic vista with deep foreground',
  'tight interior detail filling the frame',
  'elevated three-quarter view looking into the room',
  'low-angle perspective looking up at windows',
  'figure-ground silhouette composition with negative space',
  'symmetrical center-frame like a stage',
  'diagonal asymmetric framing with off-center subject',
  'over-the-shoulder intimate viewpoint',
];
