#!/bin/bash
# install-agent.sh — install com.eventpulse.agent.plist into ~/Library/LaunchAgents.
#
# Idempotent: safe to run multiple times.
#
#   ./scripts/install-agent.sh           # install + load
#   ./scripts/install-agent.sh --uninstall
#
# After install:
#   launchctl list | grep eventpulse.agent
#   cat /tmp/com.eventpulse.agent.out.log
#   curl http://localhost:8787/agent/suggested-prompts?client_user_id=$(uuidgen)

set -eu

PROJECT_ROOT="${PROJECT_ROOT:-/Volumes/2TB filer/NEWSTRUCTURE-COPY}"
PLIST_SRC="$PROJECT_ROOT/scripts/com.eventpulse.agent.plist"
PLIST_DEST="$HOME/Library/LaunchAgents/com.eventpulse.agent.plist"
WRAPPER_DEST="$HOME/bin/run-agent.sh"
LABEL="com.eventpulse.agent"

if [ ! -f "$PLIST_SRC" ]; then
  echo "ERROR: $PLIST_SRC not found" >&2
  exit 1
fi

if [ "${1:-}" = "--uninstall" ]; then
  echo "[install-agent] unloading $LABEL"
  launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
  launchctl unload "$PLIST_DEST" 2>/dev/null || true
  rm -f "$PLIST_DEST" "$WRAPPER_DEST"
  echo "[install-agent] removed $PLIST_DEST and $WRAPPER_DEST"
  exit 0
fi

# 1. Self-contained wrapper at ~/bin (launchd sandbox blocks exec of
#    scripts on /Volumes/2TB filer; reads/writes to /Volumes still work).
mkdir -p "$(dirname "$WRAPPER_DEST")"
cat > "$WRAPPER_DEST" <<WRAPPER
#!/bin/bash
# Auto-generated by scripts/install-agent.sh — DO NOT EDIT BY HAND.
# Edit scripts/install-agent.sh instead and re-run it to regenerate.
set -eu
PROJECT_ROOT="$PROJECT_ROOT"
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:\$HOME/.local/bin:\$PATH"
cd "\$PROJECT_ROOT"
echo "[run-agent] PID=\$\$ \$(date -u +%Y-%m-%dT%H:%M:%SZ) starting argv=\$*"
exec npx tsx 08-Agent/server.ts "\$@"
WRAPPER
chmod +x "$WRAPPER_DEST"
echo "[install-agent] wrote $WRAPPER_DEST"

# 2. Plist into ~/Library/LaunchAgents (idempotent — unload first).
mkdir -p "$(dirname "$PLIST_DEST")"
cp "$PLIST_SRC" "$PLIST_DEST"

launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
launchctl unload "$PLIST_DEST" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST_DEST" 2>&1 || \
  launchctl load -w "$PLIST_DEST"

echo "[install-agent] installed $PLIST_DEST"
echo "[install-agent] loaded $LABEL"
echo
echo "Verify with:"
echo "  launchctl list | grep $LABEL"
echo "  cat /tmp/com.eventpulse.agent.out.log"
echo "  curl -sS \"http://localhost:8787/agent/suggested-prompts?client_user_id=\$(uuidgen)\""